server:
  port: 8101

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: JobSearch
#  mvc:
#    static-path-pattern: /static/**
  freemarker:
    expose-session-attributes: true

#  DB
  datasource:
    url: jdbc:h2:./db/JobSearch;AUTO_SERVER=TRUE
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

# Email
  mail:
    host: smtp.gmail.com
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



logging:
  level:
    org.springframework.security: DEBUG
    root: info
    kg.job.jobsearch: debug
    com.zaxxer.hikari: error
    org.apache.tomcat: error
    liquibase: info
  file:
    path: logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


